version: '2'

services:

  app:
    build: .
    container_name: "wildfly"
    image: "wildfly"
    depends_on:
      - db
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console

  db:
    container_name: "mariadb"
    image: "mariadb:latest"
    environment:
      - MYSQL_DATABASE=shopdb
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=maria
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./script/:/docker-entrypoint-initdb.d/ # init database
    expose:
      - "3306"

networks:
    default:
        driver: bridge
